git:
  depth: 1

matrix:
  include:

    - os: linux
      language: cpp
      dist: trusty
      sudo: required
      install:
        - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
        - sudo add-apt-repository ppa:beineri/opt-qt58-trusty -y
        - sudo apt-get update -q
        - sudo apt-get install g++-6 qt58base -y
      script:
        - mkdir build && cd build
        - cmake -DCMAKE_C_COMPILER=gcc-6 -DCMAKE_CXX_COMPILER=g++-6 -DCMAKE_PREFIX_PATH=/opt/qt58/lib/cmake ..
        - cmake --build .

    - os: osx
      language: cpp
      osx_image: xcode8.2
      install:
        - brew update
        - brew install qt5
      script:
        - mkdir build && cd build
        - cmake -DCMAKE_PREFIX_PATH=/usr/local/opt/qt5/lib/cmake ..
        - cmake --build .
